### ISSUE TITLE
StringWriter throwing error while serializing null if encoding is DictionaryV2

### ISSUE THREAD

**Issue by riazraza** [ddrinka/ApacheOrcDotNet#2]
Hi,

Let me take a moment to thank you for your work, it has helped us a lot.

There is this issue I have found while serializing a string column which has enough duplicates to get encoding selected as DictionaryV2 and has a null value too. StringWriter.WriteDictionaryEncodedData() method throws error in such case on below line since value is null.
`var stringValue = sortedDictionary[value.Id];`

I tried replacing the above code with 
`var stringValue = value != null ? sortedDictionary[value.Id] : null;`

It did serialize the data, but showed empty string when I query it through Hive. 

Thanks again, let me know if I can be of any help in fixing this issue.

**Comment by ddrinka** [comment]
@riazraza Let me take a look at this.

May I ask if you're working on an Open Source project?  ApachOrcDotNet is obviously not complete, so if you've written some code to pull together the components into something working and useful, I'd be really interested to see that.

**Comment by riazraza** [comment]
No @ddrinka, I am using your code for a private enterprise application to serialize data to ORC format and then use it in Hadoop stack. But if you are willing to take this library further, I'd be glad to help you out.

**Comment by ddrinka** [comment]
Replicated issue in https://github.com/ddrinka/ApacheOrcDotNet/commit/7193bc7650afc0f65f12d57de7c72dd84b2b83c2

**Comment by ddrinka** [comment]
@riazraza Let me know if this fixes your issue.  I wasn't able to replicate the "empty string" behavior, but I haven't tested these changes in hive.

**Comment by ddrinka** [comment]
@riazraza I identified two other issues with the Dictionary implementation.  See https://github.com/ddrinka/ApacheOrcDotNet/commit/87775956287f5b1ecaeb31bd2d692a3cf97df6a9 and https://github.com/ddrinka/ApacheOrcDotNet/commit/02fe74335ad52854cd81b3afe630dc740ec3cc21
