### ISSUE TITLE
Decimal serialization is not working for Null values

### ISSUE THREAD

**Issue by riazraza** [ddrinka/ApacheOrcDotNet#3]
Hi again,

I serialized a class with nullable decimal fields and some rows had null as values for these fields. While reading data from the serialized file using Hive, it threw the following error.

>  Caused by: java.io.EOFException: Read past end of bit field from bit reader current: 0 bits left: 0 bit size: 1 from byte rle literal used: 0/0 from compressed stream Stream for column 8 kind PRESENT position: 0 length: 0 range: 0 offset: 0 limit: 0
> 	at org.apache.orc.impl.BitFieldReader.readByte(BitFieldReader.java:52)
> 	at org.apache.orc.impl.BitFieldReader.next(BitFieldReader.java:63)
> 	at org.apache.orc.impl.TreeReaderFactory$TreeReader.nextVector(TreeReaderFactory.java:180)
> 	at org.apache.orc.impl.TreeReaderFactory$DecimalTreeReader.nextVector(TreeReaderFactory.java:1111)
> 	at org.apache.orc.impl.ConvertTreeReaderFactory$DecimalFromDecimalTreeReader.nextVector(ConvertTreeReaderFactory.java:1432)
> 	at org.apache.orc.impl.TreeReaderFactory$StructTreeReader.nextBatch(TreeReaderFactory.java:1776)
> 	at org.apache.orc.impl.RecordReaderImpl.nextBatch(RecordReaderImpl.java:1071)

This even prevents Hive to read data from other rows which does have non-null values.

**Comment by ddrinka** [comment]
@riazraza Thanks for the report.  Have you pulled the new code base?  I found a number of bugs with some of the RLE encoding and fixed the ones I could identify.

To find these issues I've had to recreate the run of data that demonstrated the bug.  Are you able to refine your data down to the region that is causing the issue?

**Comment by riazraza** [comment]
Hey Douglas,

It's working with the latest code, thanks for the fix. You can close this issue.
